### ISSUE TITLE
error in installation

### ISSUE THREAD

**Issue by singhaidotnish** [errbotio/err-code#1]
purpose of using err-codebot is to send messages via javascript to users on openfire. In fulfilling the purpose i am trying this tool. ( Correct me if this is not the right tool ). 

But by running c:\Python27\Lib\site-packages\errbot>err.py, following error occurs. ( see image ).

![error_errbot](https://cloud.githubusercontent.com/assets/1680449/3373035/314b7504-fbb0-11e3-9fb8-84fd814e5963.png)

Question
1. Will this tool help server the purpose of send messages from a javascript ( or python ) script. 
1. How do i go ahead of this error.

**Comment by gbin** [comment]
2 things... 
1. the error doesn't seem to be related to err-codebot directly (basically err tells you that it cannot open its db, maybe because another instance is running or it doesn't have the right to write in the directory or something).
2. err-codebot is more like a plugin to be able to execute code in a sandboxed environment while chatting (to show an idiom in a language or something like that). Sandboxed as it cannot interact with the external world at all.

It is not clear to what you want to achieve : err can connect to openfire and you want to be able to send a message to err from a web page so it can relay it to a specific chatroom ?
